### ISSUE TITLE
glob pattern matching not recursive

### ISSUE THREAD

**Issue by jparklev** [alexfertel/bulloak#33]
I would expect `./**/*.tree` to match all subdirectories, but I had to do `./**/**/**/*.tree` to capture a file at the path `./test/perps-market-manager/create-market/createMarket.tree` https://github.com/sense-finance/perps-v1/pull/15/commits/6fb8051af25202f8a47a3ab092491c159385efa6

**Comment by jparklev** [comment]
all good. was using it via `make` and was running into things unrelated to `bulloak`

**Comment by alexfertel** [comment]
Nice! It's great when an issue solves itself, hehe.
