### ISSUE TITLE
Four spaces for indenting level

### ISSUE THREAD

**Issue by PaulRBerg** [alexfertel/bulloak#40]
The code generated by `bulloak scaffold` contains only 2 spaces.

But the community standard is to use 4 spaces for indenting Solidity code. Docs reference:

https://docs.soliditylang.org/en/v0.8.21/style-guide.html#indentation

**Comment by alexfertel** [comment]
Oh, we need to change the defaults then. Note that this is configurable right now with the `-i` flag.

We should also probably add a configurable formatting step, i.e. running `forge fmt` on the output.

**Comment by alexfertel** [comment]
Resolved in 5535ee0566111a11c3be000254de70f4fa0edb5e.

We now use `forge-fmt` to format outputted solidity code.
