### ISSUE TITLE
Print file and line number where mismatch is found

### ISSUE THREAD

**Issue by PaulRBerg** [alexfertel/bulloak#43]
If I run `bulloak check` from the root of the project, like this:

```sh
$ bulloak check ./**/*.tree
```

And there is a mismatch, I get an error log like this:

```text
Codegen not found: Couldn't find a corresponding element for "test_WhenXIsTrue" in the solidity file.
```

This is vague. It tells me neither the file in nor the line number where the mismatch was found.

For maximum clarity, Bulloak should print this information to the terminal.

**Comment by alexfertel** [comment]
This should be way better! Take it for a spin and lmk if you find any bugs.

**Comment by PaulRBerg** [comment]
Beautiful!

```text
bulloak check ./**/*.tree
•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
check failed: couldn't find a corresponding element for "test_WhenXIsTrue" in the Solidity file
file: ./test/04-given-when/givenWhen.tree | line: 7

error: 1 check failed. See details above.
```
