### ISSUE TITLE
Bulloak fails when word ‘when’ is used deep in the ‘It’ leaf

### ISSUE THREAD

**Issue by matmilbury** [alexfertel/bulloak#54]
```tree
Foo
└── It reverts when X.
```

Running `bulloak scaffold Foo.tree` results in an error: `bulloak error: invalid identifier: .`.

I understand it’s because bulloak sees the word ‘when’ in the leaf name and thinks it’s a *condition* instead of an *action*.

While I understand I could write:

```tree
Foo
└── When X
    └── It reverts.
```

I don’t like that because then the *action* statement becomes a comment which is not checked with `bulloak check` if removed.

Besides, there are legitimate usecases for the word ‘when’ used to describe the action.

Expected behavior: The word ‘when’ has a special meaning only at the beginning of a leaf name.

**Comment by alexfertel** [comment]
> I understand it’s because bulloak sees the word ‘when’ in the leaf name and thinks it’s a condition instead of an action.

Ah, not exactly. It's because top-level actions are scaffolded as tests, and thus must be valid identifiers.

**Comment by matmilbury** [comment]
Hmmm… sort of. 

But then why

```tree
Foo
└── It reverts when X.
```

fails while

```tree
Foo
└── It reverts X.
```

works?

**Comment by alexfertel** [comment]
Ooh, that's because of a parsing error. Great catch! it enters identifier mode in the tokenizer after the `when` token. I'll make some time to fix it.

**Comment by alexfertel** [comment]
Okay, finally had time to fix this! You can check it [here].(https://github.com/alexfertel/bulloak/commit/488fb6351b49da2c71ce09cd1a06b572988d03c9)

Will publish a new version in a few.
