### ISSUE TITLE
Bulloak scaffold panics when `,` in the leaf

### ISSUE THREAD

**Issue by matmilbury** [alexfertel/bulloak#58]
Given the following tree:

```
DynamicIds_createMintId
└── it hashes the payload, zeros last 16 bytes and returns a number
```

Actual result: `bulloak scaffold` panics:

```
thread 'main' panicked at /home/john/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bulloak-0.6.3/src/scaffold/mod.rs:119:38:
should format the emitted solidity code: Fmt(Error)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Expected result: bulloak removes the `,` character(s) and generates `test_HashesThePayloadZerosLast16BytesAndReturnsANumber` test.

bulloak `0.6.4`

**Comment by alexfertel** [comment]
Okay, fixed in v0.6.5! This time I brought a crate in so that now we use the same rules as solang-parser for identifiers. Hopefully, bugs of this kind are no longer possible 🤞🏻 

Lmk if you find anything else!
