### ISSUE TITLE
Refactor: create a cfg struct to inject dep 

### ISSUE THREAD

**Issue by drgorillamd** [alexfertel/bulloak#64]
Right now, arg parsed with clap are passed as individual values to the relevant fn, as there are only 4 of them for scaffold (`w`, `f`, `s` and `S`) and 2 for check.

As more option are introduced, an ever-growing list of function parameters isn't sustainable and should rather be part of a struct (leaving the cli arg versus Bulloak.toml discussion for #38 ).

```Rust
let scaffolder = Scaffolder::new(&self.solidity_version, &self.with_vm_skip);
```
would become
```Rust
let scaffolder = Scaffolder::new(&self.cfg);
```

**Comment by alexfertel** [comment]
Resolved by https://github.com/alexfertel/bulloak/pull/67 (forgot to mention the issue in the PR description)
