### ISSUE TITLE
Bug: RevertWhen_Something doesn't apply when adding revert comments

### ISSUE THREAD

**Issue by wei3erHase** [alexfertel/bulloak#69]
The `it should revert` keyword is ignored if there is a dependant leaf comment on the branch, which causes the translated test methods to be missing the `RevertWhen`.

Context:
```
FooTest
└── When stuff is called // Comments are supported.
    └── When a condition is met
        └── It should revert.
            └── Because we shouldn't allow it.
```

Expected behaviour:
```solidity
    function test_RevertWhen_PassingAnEmptyGreetingString() external {
        // it should revert
        //     Because we shouldn't allow it.
    }
```

Actual behaviour:
```solidity
    function test_WhenPassingAnEmptyGreetingString() external {
        // it should revert
        //      Because we shouldn't allow it.
    }
```

**Comment by alexfertel** [comment]
Hey! Thanks for the bug report. It seems we had a regression somewhere along the way, you're totally right.

I'll fix it and cut a release in a few minutes.

**Comment by alexfertel** [comment]
Okay, resolved in https://github.com/alexfertel/bulloak/commit/9f151c6702882532a866395af2e61f79275e5812. If you `cargo install bulloak` again, you should get v0.7.3, which includes the fix! @wei3erHase
