### ISSUE TITLE
Comments not working correctly when placed lines after/before the tree

### ISSUE THREAD

**Issue by clauBv23** [alexfertel/bulloak#75]
Hi there,

I don't know if this is the intended behavior, but I wanted to highlight it.

I would expect comments to work correctly regardless of their placement, whether before, after, or on new lines following the code. However, it seems not to work when placed a couple of lines before or after the tree.

``` tree
// This comment doesn't work

// This comment works
HashPairTest
├── It should never revert.  // This comment also works
├── When first arg is smaller than second arg
│   └── It should match the result of `keccak256(abi.encodePacked(a,b))`.
└── When first arg is bigger than second arg
    └── It should match the result of `keccak256(abi.encodePacked(b,a))`.
// This comment works

// This comment doesn't work
```
This is particularly concerning because I'm receiving the following error:
```
•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
bulloak error: found an empty tree
file: ./test/foo.tree

warn: Could not scaffold 1 files. Check the output above or run bulloak check, which might prove helpful.
```
Meanwhile, when running `bulloak check`, I receive:
```
All checks completed successfully! No issues found.
```

awesome repo btw, congrats!!!

**Comment by alexfertel** [comment]
Ooh, nice catch! Will fix it shortly.

> awesome repo btw, congrats!!!
Thanks! Please keep the feedback coming 🙌
