### ISSUE TITLE
`Bulloak check` not working as expected

### ISSUE THREAD

**Issue by clauBv23** [alexfertel/bulloak#84]
According to the documentation, `bulloak check` should verify if the test file matches the spec. However, it doesn't seem to be working for me :(

When I try `bulloak check` in a file where the test file doesn’t match the spec,  it returns the following:
<img width="389" alt="Untitled 38" src="https://github.com/user-attachments/assets/f6fa0549-fa86-44ca-bddb-48d24ebe7083">

You can check [this repo](https://github.com/clauBv23/playingWithBulloack) to see what I mean. 

I have two `.tree` files: [one with a simple example](https://github.com/clauBv23/playingWithBulloack/tree/main/test/bulloak) and [another](https://github.com/clauBv23/playingWithBulloack/tree/main/test/bulloak-example) with the same example explained in [the documentation](https://github.com/alexfertel/bulloak?tab=readme-ov-file#check-that-your-code-and-spec-match), and they both returns the same.

Is there any specific configuration needed to make this work?

**Comment by alexfertel** [comment]
Ah, this may be a bit unintuitive, but we don't recurse into directories -- You have to pass the paths you want to check.

In that example repo, you would have to run something like `bulloak check test/bulloak/foo.tree` or `bulloak check ./**/*.tree` for it to check your specs!

**Comment by clauBv23** [comment]
Oh, it works perfectly when specifying the paths.
ty!
