### ISSUE TITLE
Ship Bulloak as a Release

### ISSUE THREAD

**Issue by smol-ninja** [alexfertel/bulloak#85]
Currently, Bulloak is shipped under the [tag category](https://github.com/alexfertel/bulloak/tags). It would be great to see it shipped as a [Software Release](https://github.com/alexfertel/bulloak/releases).

**Comment by alexfertel** [comment]
yeah, makes sense, will do as soon as I can

**Comment by alexfertel** [comment]
Hey @smol-ninja ! Just released the [latest version](https://github.com/alexfertel/bulloak/releases/tag/v0.8.0). Let me know if everything works well, if not, feel free to reopen this issue.

**Comment by smol-ninja** [comment]
Great. Thank you very much @alexfertel.
