### ISSUE TITLE
Adding `vm.skip(true)` to new test cases after scaffold

### ISSUE THREAD

**Issue by danilych** [alexfertel/bulloak#87]
I suggest adding vm.skip(true) to every new test in the newly generated test suite. This practice helps improve coverage understanding and prevents incomplete (empty) tests from being overlooked in large projects with many specific tests.

```solidity
function test_WhenNotOwnerCallFunction() external {
vm.skip(true);    
// it reverts
}
```

<img width="835" alt="image" src="https://github.com/user-attachments/assets/59e036cd-59aa-434c-a611-efcdd16fc66c">

**Comment by alexfertel** [comment]
Hey, this is currently supported by `bulloak`. You can see the closed issue [here](https://github.com/alexfertel/bulloak/issues/57)!
