### ISSUE TITLE
Add social media preview in docs site

### ISSUE THREAD

**Issue by PaulRBerg** [alexfertel/bulloak#91]
[There doesn't appear](https://metatags.io/?url=bulloak.dev) to be any social media preview now:

<img width="636" alt="SCR-20240920-lvet" src="https://github.com/user-attachments/assets/e684be11-b753-496e-8d8d-1bc8a23683d8">

**Comment by alexfertel** [comment]
oh damn, I'll fix this over the weekend! Thanks for opening the issue

**Comment by alexfertel** [comment]
Okay @PaulRBerg it's working now! https://metatags.io/?url=https://www.bulloak.dev/
