### ISSUE TITLE
should format the emitted solidity code: Fmt(Error)

### ISSUE THREAD

**Issue by 0xfave** [alexfertel/bulloak#94]
I am trying to use `scaffold` command but I am running into this issue

here is the command that I am using to 
`bulloak scaffold test/unit/tree/receive.tree`

this is the error
```shell
thread 'main' panicked at /home/fave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bulloak-foundry-0.8.0/src/scaffold/mod.rs:22:22:
should format the emitted solidity code: Fmt(Error)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I am using compiler version `0.8.25` and I also confirm that the tree files are there and also used the `fix` command to be sure there's no issue thereof

**Comment by alexfertel** [comment]
@0xfave could you share the contents of the `receive.tree` file 🙏

**Comment by 0xfave** [comment]
```receive
    └── when contract receives ETH
        └── it should emit Received event with sender and amount
```

**Comment by alexfertel** [comment]
When I try to scaffold that tree it outputs:

```
•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
bulloak error: missing a root
file: crates/bulloak/tests/scaffold/basic.tree

warn: Could not scaffold 1 files. Check the output above or run bulloak check, which might prove helpful.
```

**Comment by 0xfave** [comment]
Sorry the code block remove the root
I have corrected it

**Comment by alexfertel** [comment]
Ah, so `receive` is a Solidity keyword, so you cannot use it as a contract name! If you use `Receive` it works.

**Comment by 0xfave** [comment]
changed it and it worked.

thanks will close the issue now
